version: "3.8"
services:
  web:
    build: .
    ports:
      - "8899:8899"
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    # MEMORY LIMITS
    mem_limit: 1500m,
    mem_reservation: 400m
    memswap_limit: 1g
    oom_kill_disable: false
    # CPU LIMITS
    cpus: 1.5
    deploy:
      resources:
        limits:
          memory: 1500M
        reservations:
          memory: 400M
